[irc]
server = "irc.esper.net"
port = 6697
ssl = true

nickname = "CRY"
username = "why"
realname = "Cry before you die."

channels = "#V"

[modules]
load = ["basic", "permissions", "esolangs"]

[permissions]
vifino = "admin sudo"

[aliases]
hello = "echo 'Hello World!'"
